services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - db_data:/app/db_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

volumes:
  db_data:
